# Generated by Django 3.2.4 on 2021-06-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitCoinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bit_coin_data',
            },
        ),
    ]
