# Generated by Django 3.2.4 on 2021-06-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitCoinStatus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcoindata',
            old_name='price',
            new_name='close_price',
        ),
        migrations.AddField(
            model_name='bitcoindata',
            name='high_price',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoindata',
            name='low_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitcoindata',
            name='open_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
