# Generated by Django 3.2.4 on 2021-06-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitCoinStatus', '0003_auto_20210618_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoindata',
            name='unixtime',
            field=models.DateTimeField(null=True),
        ),
    ]
