# Generated by Django 3.2.4 on 2021-06-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BitCoinStatus', '0004_bitcoindata_unixtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoindata',
            name='unixtime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
